import React,{useState} from 'react';
import api from '../services/api';
export function LegacyReceiptRecovery({sellerId,raffleId}:{sellerId:string;raffleId:string;key?:string}){
 const empty=()=>({number:'',finalNumber:'',verificationCode:'',buyerName:'',dni:'',phone:'',issuedAt:'',price:'10'});
 const [open,setOpen]=useState(false),[receipts,setReceipts]=useState([empty()]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [reconcile,setReconcile]=useState(false),[reason,setReason]=useState(''),[move,setMove]=useState({verificationCode:'',dni:'',fromNumber:'',toNumber:''});
 const labels={number:'Número original',verificationCode:'Código original',buyerName:'Comprador',dni:'DNI',phone:'Celular (opcional)',issuedAt:'Fecha y hora de venta (Perú)',price:'Monto pagado',finalNumber:'Número final (solo si hay conflicto)'};
 async function recover(){setBusy(true);setMessage('');try{const result=await api.mutate('/tickets/recover-legacy','POST',{sellerAdminId:sellerId,raffleId,reason:reconcile?reason:undefined,relocations:reconcile&&move.verificationCode?[{...move,fromNumber:Number(move.fromNumber),toNumber:Number(move.toNumber)}]:[],receipts:receipts.map(r=>({number:Number(reconcile&&r.finalNumber?r.finalNumber:r.number),originalNumber:Number(r.number),verificationCode:r.verificationCode,buyerName:r.buyerName,dni:r.dni,phone:r.phone,price:Number(r.price),issuedAt:new Date(r.issuedAt+':00-05:00').toISOString()}))});setMessage(`Recuperación confirmada: ${result.created} incorporados; ${result.alreadyPresent} ya registrados; ${result.relocated||0} trasladados. Se conservaron los códigos originales.`);}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 return <div className="mt-4 border-t pt-3"><button type="button" className="border rounded-lg p-2 text-sm" onClick={()=>setOpen(!open)}>Recuperar comprobantes antiguos</button>{open&&<div className="mt-3 space-y-2"><p className="text-sm">Incorpore solo ventas conciliadas. Se conservan código y fecha originales; cualquier conflicto cancela el lote completo. Los celulares desconocidos pueden quedar vacíos. Los cambios de número requieren un motivo y conservan el comprador de cada QR.</p><label className="block text-sm"><input type="checkbox" checked={reconcile} disabled={busy} onChange={e=>setReconcile(e.target.checked)}/> Conciliar números en conflicto</label>{reconcile&&<fieldset className="border rounded-lg p-3 space-y-2"><legend>Traslado de un boleto existente (opcional)</legend>{(['verificationCode','dni','fromNumber','toNumber'] as const).map((key,i)=><label key={key} className="block text-xs">{['Código del boleto a trasladar','DNI del comprador a trasladar','Número actual del boleto a trasladar','Número nuevo del boleto a trasladar'][i]}<input aria-label={['Código del boleto a trasladar','DNI del comprador a trasladar','Número actual del boleto a trasladar','Número nuevo del boleto a trasladar'][i]} value={move[key]} disabled={busy} className="block border rounded p-2 w-full" onChange={e=>setMove(prev=>({...prev,[key]:e.target.value}))}/></label>)}<label className="block text-xs">Motivo de conciliación<textarea aria-label="Motivo de conciliación" value={reason} disabled={busy} className="block border rounded p-2 w-full" onChange={e=>setReason(e.target.value)}/></label></fieldset>}{receipts.map((r,i)=><fieldset key={i} className="border rounded-lg p-3 grid sm:grid-cols-2 gap-2"><legend>Comprobante {i+1}</legend>{(Object.keys(labels) as (keyof typeof labels)[]).filter(key=>key!=='finalNumber'||reconcile).map(key=><label key={key} className="text-xs">{labels[key]}<input aria-label={`${labels[key]} ${i+1}`} type={key==='issuedAt'?'datetime-local':'text'} value={r[key]} disabled={busy} className="block border rounded p-2 w-full" onChange={e=>setReceipts(prev=>prev.map((item,index)=>index===i?{...item,[key]:e.target.value}:item))}/></label>)}</fieldset>)}<button type="button" disabled={busy||receipts.length>=20} className="border rounded p-2 text-sm" onClick={()=>setReceipts(prev=>[...prev,empty()])}>Añadir comprobante</button><button type="button" disabled={busy} onClick={recover} className="bg-emerald-700 text-white rounded-lg p-2 disabled:opacity-50">Confirmar recuperación de comprobantes</button>{message&&<p role="status" className="text-sm">{message}</p>}</div>}</div>;
}
